# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GrupoIPExtracaoDeEstradas
                                 A QGIS plugin
 Buffer de Logradouros
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-20
        copyright            : (C) 2023 by Grupo 3
        email                : marcio.souza@ime.eb.br
                               matheus.silva@ime.eb.br
                               romeu.peris@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Grupo IP Extração De Estradas'
__date__ = '2023-04-16'
__copyright__ = '(C) 2023 by Grupo IP Extração De Estradas'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProgramacaoAplicadaGrupo3 class from file ProgramacaoAplicadaGrupo3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .grupo_ip_extracao_de_estradas import BufferLogradourosPuglin
    return BufferLogradourosPuglin()
